name: roboshop
services: 
  mongodb:
    build: ./mongodb
    image: venkey57/mongodb:v1 #docker build -t joindevops/mongodb:v1 # [registry/]repository/image-name:tag
    container_name: mongodb    # docker run -d --network roboshop joindevops/mongodb:v1

  catalogue:
    build: ./catalogue
    image: venkey57/catalogue:v1
    container_name: catalogue
    depends_on:
    - mongodb

  frontend:
    build: ./frontend
    image: venkey57/frontend:v1
    container_name: frontend
    ports:
    - "80:80"
    depends_on:
    - catalogue

networks:
  default: # this means all the services in this file use this network
    name: roboshop
    driver: bridge
    external: false # if true it should be created manually, if false docker creates this network
  